#if UNITY_EDITOR

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using Slate;
using UnityEditor;
using UnityEngine;
using Path = System.IO.Path;

namespace Hoshino
{
    public static class SkillSerializationCodeGenerator
    {
        private const string RuntimeOutputPath = "Assets/Scripts/Generated/Skill/Runtime/SkillGeneratedSerialization.cs";
        private const string EditorOutputPath = "Assets/Scripts/Generated/Skill/Editor/SkillGeneratedEditorSerialization.cs";
        private const string LegacyRuntimeOutputPath = "Assets/Scripts/Skill/Skill/Generated/SkillGeneratedSerialization.cs";
        private const string LegacyEditorOutputPath = "Assets/Scripts/Skill/Skill/Editor/Generated/SkillGeneratedEditorSerialization.cs";

        [MenuItem("Tools/Hoshino/Generate Skill Serialization Code")]
        public static void Generate()
        {
            List<SkillTypeInfo> groups = SkillCodeGenUtilities.GatherTypes(SkillSerializedTypeKind.Group);
            List<SkillTypeInfo> tracks = SkillCodeGenUtilities.GatherTypes(SkillSerializedTypeKind.Track);
            List<SkillTypeInfo> clips = SkillCodeGenUtilities.GatherTypes(SkillSerializedTypeKind.Clip);
            List<SkillTypeInfo> specialDatas = SkillCodeGenUtilities.GatherTypes(SkillSerializedTypeKind.SpecialData);

            foreach (SkillTypeInfo clip in clips)
            {
                clip.CustomFields = SkillCodeGenUtilities.GetCustomFields(clip.Type);
                foreach (FieldInfo field in clip.CustomFields)
                    SkillCodeGenUtilities.ValidateCustomField(field);
            }

            foreach (SkillTypeInfo specialData in specialDatas)
            {
                specialData.CustomFields = SkillCodeGenUtilities.GetCustomFields(specialData.Type);
                foreach (FieldInfo field in specialData.CustomFields)
                    SkillCodeGenUtilities.ValidateCustomField(field);
            }

            SkillCodeGenUtilities.ValidateIds(groups, "group");
            SkillCodeGenUtilities.ValidateIds(tracks, "track");
            SkillCodeGenUtilities.ValidateIds(clips, "clip");
            SkillCodeGenUtilities.ValidateIds(specialDatas, "specialData");
            SkillCodeGenUtilities.ValidateGlobalIds(groups, tracks, clips, specialDatas);
            SkillCodeGenUtilities.ValidateGeneratedNames(groups.Concat(tracks).Concat(clips), SkillCodeGenUtilities.GetIdName, "generated id constant");
            SkillCodeGenUtilities.ValidateGeneratedNames(clips, SkillCodeGenUtilities.GetNodeDataName, "generated node data type");
            SkillCodeGenUtilities.ValidateGeneratedNames(specialDatas, SkillCodeGenUtilities.GetSpecialDataName, "generated special data type");

            SkillCodeGenUtilities.EnsureFolder(Path.GetDirectoryName(RuntimeOutputPath));
            SkillCodeGenUtilities.EnsureFolder(Path.GetDirectoryName(EditorOutputPath));
            File.WriteAllText(RuntimeOutputPath, GenerateRuntimeCode(groups, tracks, clips, specialDatas));
            File.WriteAllText(EditorOutputPath, GenerateEditorCode(groups, tracks, clips, specialDatas));
            SkillCodeGenUtilities.DeleteLegacyGeneratedFile(LegacyRuntimeOutputPath);
            SkillCodeGenUtilities.DeleteLegacyGeneratedFile(LegacyEditorOutputPath);
            SkillCodeGenUtilities.DeleteLegacyGeneratedFolderIfEmpty(Path.GetDirectoryName(LegacyRuntimeOutputPath));
            SkillCodeGenUtilities.DeleteLegacyGeneratedFolderIfEmpty(Path.GetDirectoryName(LegacyEditorOutputPath));
            SkillGeneratedSerializationServices.Reset();
            AssetDatabase.Refresh();
        }

        private static string GenerateRuntimeCode(List<SkillTypeInfo> groups, List<SkillTypeInfo> tracks, List<SkillTypeInfo> clips, List<SkillTypeInfo> specialDatas)
        {
            StringBuilder sb = new();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.IO;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine("namespace Hoshino");
            sb.AppendLine("{");
            sb.AppendLine("    public static class SkillGeneratedIds");
            sb.AppendLine("    {");
            foreach (SkillTypeInfo item in groups.Concat(tracks).Concat(clips).Concat(specialDatas))
                sb.AppendLine($"        public const uint {SkillCodeGenUtilities.GetIdName(item)} = {item.Id}u;");
            sb.AppendLine("    }");
            sb.AppendLine();

            foreach (SkillTypeInfo clip in clips)
                AppendNodeDataStruct(sb, clip);

            foreach (SkillTypeInfo specialData in specialDatas)
                AppendSpecialDataStruct(sb, specialData);

            sb.AppendLine("    public sealed class SkillGeneratedRuntimeSerialization : ISkillGeneratedRuntimeSerialization");
            sb.AppendLine("    {");
            sb.AppendLine("        public void WriteBoxed(BinaryWriter writer, uint clipId, object data)");
            sb.AppendLine("        {");
            sb.AppendLine("            SkillGeneratedNodeDataBlob.WriteBoxed(writer, clipId, data);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public bool TryRead<TData>(SkillDefinition skill, SkillRuntimeNode node, out TData data) where TData : struct");
            sb.AppendLine("        {");
            sb.AppendLine("            return SkillGeneratedNodeDataBlob.TryRead(skill, node, out data);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public bool IsClipKnown(uint clipId)");
            sb.AppendLine("        {");
            sb.AppendLine("            return SkillGeneratedNodeDataBlob.IsClipKnown(clipId);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public void WriteSpecialDataBoxed(BinaryWriter writer, uint specialDataId, object data)");
            sb.AppendLine("        {");
            sb.AppendLine("            SkillGeneratedSpecialDataBlob.WriteBoxed(writer, specialDataId, data);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public bool TryReadSpecialData<TData>(SkillDefinition skill, SkillRuntimeSpecialData entry, out TData data) where TData : struct");
            sb.AppendLine("        {");
            sb.AppendLine("            return SkillGeneratedSpecialDataBlob.TryRead(skill, entry, out data);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public bool IsSpecialDataKnown(uint specialDataId)");
            sb.AppendLine("        {");
            sb.AppendLine("            return SkillGeneratedSpecialDataBlob.IsKnown(specialDataId);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine("    public static class SkillGeneratedNodeDataBlob");
            sb.AppendLine("    {");
            sb.AppendLine("        public static void WriteBoxed(BinaryWriter writer, uint clipId, object data)");
            sb.AppendLine("        {");
            sb.AppendLine("            switch (clipId)");
            sb.AppendLine("            {");
            foreach (SkillTypeInfo clip in clips)
            {
                string dataName = SkillCodeGenUtilities.GetNodeDataName(clip);
                sb.AppendLine($"                case SkillGeneratedIds.{SkillCodeGenUtilities.GetIdName(clip)}:");
                sb.AppendLine("                {");
                sb.AppendLine($"                    {dataName} value = data is {dataName} typed ? typed : default;");
                foreach (FieldInfo field in clip.CustomFields)
                    sb.AppendLine($"                    {SkillCodeGenUtilities.WriteStatement(field.FieldType, $"value.{field.Name}", "writer")}");
                sb.AppendLine("                    break;");
                sb.AppendLine("                }");
            }
            sb.AppendLine("                default: throw new InvalidOperationException($\"No generated node data writer for clip id {clipId}.\");");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        public static bool TryRead<TData>(SkillDefinition skill, SkillRuntimeNode node, out TData data) where TData : struct");
            sb.AppendLine("        {");
            sb.AppendLine("            if (skill == null)");
            sb.AppendLine("            {");
            sb.AppendLine("                data = default;");
            sb.AppendLine("                return false;");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            object cached = skill.GetCachedNodeData(node.NodeId);");
            sb.AppendLine("            if (cached is TData cachedData)");
            sb.AppendLine("            {");
            sb.AppendLine("                data = cachedData;");
            sb.AppendLine("                return true;");
            sb.AppendLine("            }");
            sb.AppendLine("            if (cached != null)");
            sb.AppendLine("            {");
            sb.AppendLine("                data = default;");
            sb.AppendLine("                return false;");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            byte[] blob = skill.NodeDataBlob;");
            sb.AppendLine("            if (blob == null || node.DataOffset < 0 || node.DataLength < 0 || (long)node.DataOffset + node.DataLength > blob.Length)");
            sb.AppendLine("            {");
            sb.AppendLine("                data = default;");
            sb.AppendLine("                return false;");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            using MemoryStream stream = new(blob, node.DataOffset, node.DataLength, false);");
            sb.AppendLine("            using BinaryReader reader = new(stream);");
            sb.AppendLine("            object value;");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine("                value = ReadBoxed(reader, node.ClipId);");
            sb.AppendLine("            }");
            sb.AppendLine("            catch (Exception)");
            sb.AppendLine("            {");
            sb.AppendLine("                data = default;");
            sb.AppendLine("                return false;");
            sb.AppendLine("            }");
            sb.AppendLine("            if (stream.Position != node.DataLength)");
            sb.AppendLine("            {");
            sb.AppendLine("                data = default;");
            sb.AppendLine("                return false;");
            sb.AppendLine("            }");
            sb.AppendLine("            if (!(value is TData typed))");
            sb.AppendLine("            {");
            sb.AppendLine("                data = default;");
            sb.AppendLine("                return false;");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            skill.SetCachedNodeData(node.NodeId, typed);");
            sb.AppendLine("            data = typed;");
            sb.AppendLine("            return true;");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        private static object ReadBoxed(BinaryReader reader, uint clipId)");
            sb.AppendLine("        {");
            sb.AppendLine("            switch (clipId)");
            sb.AppendLine("            {");
            foreach (SkillTypeInfo clip in clips)
            {
                sb.AppendLine($"                case SkillGeneratedIds.{SkillCodeGenUtilities.GetIdName(clip)}:");
                sb.AppendLine($"                    return new {SkillCodeGenUtilities.GetNodeDataName(clip)} {{ {string.Join(", ", clip.CustomFields.Select(f => $"{f.Name} = {SkillCodeGenUtilities.ReadExpression(f.FieldType, "reader")}"))} }};");
            }
            sb.AppendLine("                default: throw new InvalidOperationException($\"No generated node data reader for clip id {clipId}.\");");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        public static bool IsClipKnown(uint clipId)");
            sb.AppendLine("        {");
            if (clips.Count > 0)
            {
                sb.AppendLine("            switch (clipId)");
                sb.AppendLine("            {");
                foreach (SkillTypeInfo clip in clips)
                {
                    sb.AppendLine($"                case SkillGeneratedIds.{SkillCodeGenUtilities.GetIdName(clip)}:");
                    sb.AppendLine("                    return true;");
                }
                sb.AppendLine("                default:");
                sb.AppendLine("                    return false;");
                sb.AppendLine("            }");
            }
            else
            {
                sb.AppendLine("            return false;");
            }
            sb.AppendLine("        }");
            sb.AppendLine();
            SkillCodeGenUtilities.AppendArrayHelpers(sb, "        ");
            SkillCodeGenUtilities.AppendVectorHelpers(sb, "        ");
            sb.AppendLine("    }");
            sb.AppendLine();

            AppendSpecialDataBlob(sb, specialDatas);

            sb.AppendLine("}");
            return sb.ToString();
        }

        private static void AppendSpecialDataStruct(StringBuilder sb, SkillTypeInfo specialData)
        {
            sb.AppendLine("    [Serializable]");
            sb.AppendLine($"    public struct {SkillCodeGenUtilities.GetSpecialDataName(specialData)}");
            sb.AppendLine("    {");
            foreach (FieldInfo field in specialData.CustomFields)
                sb.AppendLine($"        public {SkillCodeGenUtilities.GetTypeName(field.FieldType)} {field.Name};");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        /// <summary>生成 SkillGeneratedSpecialDataBlob 类，镜像 NodeDataBlob 但读 SpecialDataBlob + SkillRuntimeSpecialData。</summary>
        private static void AppendSpecialDataBlob(StringBuilder sb, List<SkillTypeInfo> specialDatas)
        {
            sb.AppendLine("    public static class SkillGeneratedSpecialDataBlob");
            sb.AppendLine("    {");
            sb.AppendLine("        public static void WriteBoxed(BinaryWriter writer, uint specialDataId, object data)");
            sb.AppendLine("        {");
            sb.AppendLine("            switch (specialDataId)");
            sb.AppendLine("            {");
            foreach (SkillTypeInfo specialData in specialDatas)
            {
                string dataName = SkillCodeGenUtilities.GetSpecialDataName(specialData);
                sb.AppendLine($"                case SkillGeneratedIds.{SkillCodeGenUtilities.GetIdName(specialData)}:");
                sb.AppendLine("                {");
                sb.AppendLine($"                    {dataName} value = data is {dataName} typed ? typed : default;");
                foreach (FieldInfo field in specialData.CustomFields)
                    sb.AppendLine($"                    {SkillCodeGenUtilities.WriteStatement(field.FieldType, $"value.{field.Name}", "writer")}");
                sb.AppendLine("                    break;");
                sb.AppendLine("                }");
            }
            sb.AppendLine("                default: throw new InvalidOperationException($\"No generated special data writer for id {specialDataId}.\");");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        public static bool TryRead<TData>(SkillDefinition skill, SkillRuntimeSpecialData entry, out TData data) where TData : struct");
            sb.AppendLine("        {");
            sb.AppendLine("            if (skill == null || entry.DataLength <= 0)");
            sb.AppendLine("            {");
            sb.AppendLine("                data = default;");
            sb.AppendLine("                return false;");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            object cached = skill.GetCachedSpecialData(entry.SpecialDataId);");
            sb.AppendLine("            if (cached is TData cachedData)");
            sb.AppendLine("            {");
            sb.AppendLine("                data = cachedData;");
            sb.AppendLine("                return true;");
            sb.AppendLine("            }");
            sb.AppendLine("            if (cached != null)");
            sb.AppendLine("            {");
            sb.AppendLine("                data = default;");
            sb.AppendLine("                return false;");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            byte[] blob = skill.SpecialDataBlob;");
            sb.AppendLine("            if (blob == null || entry.DataOffset < 0 || (long)entry.DataOffset + entry.DataLength > blob.Length)");
            sb.AppendLine("            {");
            sb.AppendLine("                data = default;");
            sb.AppendLine("                return false;");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            using MemoryStream stream = new(blob, entry.DataOffset, entry.DataLength, false);");
            sb.AppendLine("            using BinaryReader reader = new(stream);");
            sb.AppendLine("            object value;");
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine("                value = ReadBoxed(reader, entry.SpecialDataTypeId);");
            sb.AppendLine("            }");
            sb.AppendLine("            catch (Exception)");
            sb.AppendLine("            {");
            sb.AppendLine("                data = default;");
            sb.AppendLine("                return false;");
            sb.AppendLine("            }");
            sb.AppendLine("            if (stream.Position != entry.DataLength)");
            sb.AppendLine("            {");
            sb.AppendLine("                data = default;");
            sb.AppendLine("                return false;");
            sb.AppendLine("            }");
            sb.AppendLine("            if (!(value is TData typed))");
            sb.AppendLine("            {");
            sb.AppendLine("                data = default;");
            sb.AppendLine("                return false;");
            sb.AppendLine("            }");
            sb.AppendLine();
            sb.AppendLine("            skill.SetCachedSpecialData(entry.SpecialDataId, typed);");
            sb.AppendLine("            data = typed;");
            sb.AppendLine("            return true;");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        private static object ReadBoxed(BinaryReader reader, uint specialDataId)");
            sb.AppendLine("        {");
            sb.AppendLine("            switch (specialDataId)");
            sb.AppendLine("            {");
            foreach (SkillTypeInfo specialData in specialDatas)
            {
                sb.AppendLine($"                case SkillGeneratedIds.{SkillCodeGenUtilities.GetIdName(specialData)}:");
                sb.AppendLine($"                    return new {SkillCodeGenUtilities.GetSpecialDataName(specialData)} {{ {string.Join(", ", specialData.CustomFields.Select(f => $"{f.Name} = {SkillCodeGenUtilities.ReadExpression(f.FieldType, "reader")}"))} }};");
            }
            sb.AppendLine("                default: throw new InvalidOperationException($\"No generated special data reader for id {specialDataId}.\");");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        public static bool IsKnown(uint specialDataId)");
            sb.AppendLine("        {");
            if (specialDatas.Count > 0)
            {
                sb.AppendLine("            switch (specialDataId)");
                sb.AppendLine("            {");
                foreach (SkillTypeInfo specialData in specialDatas)
                {
                    sb.AppendLine($"                case SkillGeneratedIds.{SkillCodeGenUtilities.GetIdName(specialData)}:");
                    sb.AppendLine("                    return true;");
                }
                sb.AppendLine("                default:");
                sb.AppendLine("                    return false;");
                sb.AppendLine("            }");
            }
            else
            {
                sb.AppendLine("            return false;");
            }
            sb.AppendLine("        }");
            sb.AppendLine("    }");
        }

        private static string GenerateEditorCode(List<SkillTypeInfo> groups, List<SkillTypeInfo> tracks, List<SkillTypeInfo> clips, List<SkillTypeInfo> specialDatas)
        {
            StringBuilder sb = new();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#if UNITY_EDITOR");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.IO;");
            sb.AppendLine("using Slate;");
            sb.AppendLine("using UnityEditor;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine("namespace Hoshino");
            sb.AppendLine("{");
            sb.AppendLine("    public sealed class SkillGeneratedEditorSerialization : ISkillGeneratedEditorSerialization");
            sb.AppendLine("    {");
            AppendTryGetIdMethod(sb, "Group", groups);
            AppendTryGetIdMethod(sb, "Track", tracks);
            AppendTryGetIdMethod(sb, "Clip", clips);
            AppendTryGetIdMethod(sb, "SpecialData", specialDatas);
            AppendFactories(sb, groups, tracks, clips, specialDatas);
            AppendCustomDataMethods(sb, clips);
            AppendSpecialDataMethods(sb, specialDatas);
            AppendEditorHelpers(sb);
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("#endif");
            return sb.ToString();
        }

        private static void AppendNodeDataStruct(StringBuilder sb, SkillTypeInfo clip)
        {
            sb.AppendLine("    [Serializable]");
            sb.AppendLine($"    public struct {SkillCodeGenUtilities.GetNodeDataName(clip)}");
            sb.AppendLine("    {");
            foreach (FieldInfo field in clip.CustomFields)
                sb.AppendLine($"        public {SkillCodeGenUtilities.GetTypeName(field.FieldType)} {field.Name};");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        private static void AppendTryGetIdMethod(StringBuilder sb, string kindName, List<SkillTypeInfo> items)
        {
            sb.AppendLine($"        public bool TryGet{kindName}Id(Type type, out uint id)");
            sb.AppendLine("        {");
            foreach (SkillTypeInfo item in items)
                sb.AppendLine($"            if (type == typeof({SkillCodeGenUtilities.GetTypeName(item.Type)})) {{ id = SkillGeneratedIds.{SkillCodeGenUtilities.GetIdName(item)}; return true; }}");
            sb.AppendLine("            id = 0u;");
            sb.AppendLine("            return false;");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void AppendFactories(StringBuilder sb, List<SkillTypeInfo> groups, List<SkillTypeInfo> tracks, List<SkillTypeInfo> clips, List<SkillTypeInfo> specialDatas)
        {
            sb.AppendLine("        public CutsceneGroup CreateGroup(uint id, Cutscene cutscene)");
            sb.AppendLine("        {");
            sb.AppendLine("            Type type = id switch");
            sb.AppendLine("            {");
            foreach (SkillTypeInfo item in groups)
                sb.AppendLine($"                SkillGeneratedIds.{SkillCodeGenUtilities.GetIdName(item)} => typeof({SkillCodeGenUtilities.GetTypeName(item.Type)}),");
            sb.AppendLine("                _ => null");
            sb.AppendLine("            };");
            sb.AppendLine("            if (type == null) return null;");
            sb.AppendLine("            GameObject go = new(type.Name);");
            sb.AppendLine("            Undo.RegisterCreatedObjectUndo(go, \"Import Skill Group\");");
            sb.AppendLine("            Undo.SetTransformParent(go.transform, cutscene.groupsRoot, \"Import Skill Group\");");
            sb.AppendLine("            go.transform.localPosition = Vector3.zero;");
            sb.AppendLine("            return (CutsceneGroup)go.AddComponent(type);");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        public CutsceneTrack CreateTrack(uint id, CutsceneGroup group)");
            sb.AppendLine("        {");
            sb.AppendLine("            Type type = id switch");
            sb.AppendLine("            {");
            foreach (SkillTypeInfo item in tracks)
                sb.AppendLine($"                SkillGeneratedIds.{SkillCodeGenUtilities.GetIdName(item)} => typeof({SkillCodeGenUtilities.GetTypeName(item.Type)}),");
            sb.AppendLine("                _ => null");
            sb.AppendLine("            };");
            sb.AppendLine("            if (type == null) return null;");
            sb.AppendLine("            GameObject go = new(type.Name);");
            sb.AppendLine("            Undo.RegisterCreatedObjectUndo(go, \"Import Skill Track\");");
            sb.AppendLine("            Undo.SetTransformParent(go.transform, group.transform, \"Import Skill Track\");");
            sb.AppendLine("            go.transform.localPosition = Vector3.zero;");
            sb.AppendLine("            CutsceneTrack track = (CutsceneTrack)go.AddComponent(type);");
            sb.AppendLine("            track.PostCreate(group);");
            sb.AppendLine("            return track;");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        public ActionClip CreateClip(uint id, CutsceneTrack track)");
            sb.AppendLine("        {");
            sb.AppendLine("            Type type = id switch");
            sb.AppendLine("            {");
            foreach (SkillTypeInfo item in clips)
                sb.AppendLine($"                SkillGeneratedIds.{SkillCodeGenUtilities.GetIdName(item)} => typeof({SkillCodeGenUtilities.GetTypeName(item.Type)}),");
            sb.AppendLine("                _ => null");
            sb.AppendLine("            };");
            sb.AppendLine("            if (type == null) return null;");
            sb.AppendLine("            ActionClip clip = (ActionClip)Undo.AddComponent(track.gameObject, type);");
            sb.AppendLine("            clip.PostCreate(track);");
            sb.AppendLine("            return clip;");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        public object CreateSpecialData(uint id)");
            sb.AppendLine("        {");
            sb.AppendLine("            Type type = id switch");
            sb.AppendLine("            {");
            foreach (SkillTypeInfo item in specialDatas)
                sb.AppendLine($"                SkillGeneratedIds.{SkillCodeGenUtilities.GetIdName(item)} => typeof({SkillCodeGenUtilities.GetTypeName(item.Type)}),");
            sb.AppendLine("                _ => null");
            sb.AppendLine("            };");
            sb.AppendLine("            if (type == null) return null;");
            sb.AppendLine("            return Activator.CreateInstance(type);");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void AppendCustomDataMethods(StringBuilder sb, List<SkillTypeInfo> clips)
        {
            sb.AppendLine("        public object CaptureClipCustomData(uint clipId, ActionClip clip)");
            sb.AppendLine("        {");
            sb.AppendLine("            switch (clipId)");
            sb.AppendLine("            {");
            foreach (SkillTypeInfo clip in clips)
            {
                sb.AppendLine($"                case SkillGeneratedIds.{SkillCodeGenUtilities.GetIdName(clip)}:");
                sb.AppendLine("                {");
                sb.AppendLine($"                    {SkillCodeGenUtilities.GetTypeName(clip.Type)} typed = ({SkillCodeGenUtilities.GetTypeName(clip.Type)})clip;");
                sb.AppendLine($"                    return new {SkillCodeGenUtilities.GetNodeDataName(clip)} {{ {string.Join(", ", clip.CustomFields.Select(f => $"{f.Name} = typed.{f.Name}"))} }};");
                sb.AppendLine("                }");
            }
            sb.AppendLine("                default: throw new InvalidOperationException($\"No generated custom data capture for clip id {clipId}.\");");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        public void ApplyClipCustomData(uint clipId, ActionClip clip, object data)");
            sb.AppendLine("        {");
            sb.AppendLine("            switch (clipId)");
            sb.AppendLine("            {");
            foreach (SkillTypeInfo clip in clips)
            {
                string dataName = SkillCodeGenUtilities.GetNodeDataName(clip);
                sb.AppendLine($"                case SkillGeneratedIds.{SkillCodeGenUtilities.GetIdName(clip)}:");
                sb.AppendLine("                {");
                sb.AppendLine($"                    {SkillCodeGenUtilities.GetTypeName(clip.Type)} typed = ({SkillCodeGenUtilities.GetTypeName(clip.Type)})clip;");
                sb.AppendLine($"                    {dataName} value = data is {dataName} d ? d : default;");
                foreach (FieldInfo field in clip.CustomFields)
                    sb.AppendLine($"                    typed.{field.Name} = value.{field.Name};");
                sb.AppendLine("                    break;");
                sb.AppendLine("                }");
            }
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        public void WriteClipCustomData(BinaryWriter writer, uint clipId, ActionClip clip)");
            sb.AppendLine("        {");
            sb.AppendLine("            WriteClipCustomDataObject(writer, clipId, CaptureClipCustomData(clipId, clip));");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        public object ReadClipCustomData(BinaryReader reader, uint clipId)");
            sb.AppendLine("        {");
            sb.AppendLine("            switch (clipId)");
            sb.AppendLine("            {");
            foreach (SkillTypeInfo clip in clips)
            {
                sb.AppendLine($"                case SkillGeneratedIds.{SkillCodeGenUtilities.GetIdName(clip)}:");
                sb.AppendLine($"                    return new {SkillCodeGenUtilities.GetNodeDataName(clip)} {{ {string.Join(", ", clip.CustomFields.Select(f => $"{f.Name} = {SkillCodeGenUtilities.ReadExpression(f.FieldType, "reader")}"))} }};");
            }
            sb.AppendLine("                default: throw new InvalidOperationException($\"No generated custom data reader for clip id {clipId}.\");");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        private static void WriteClipCustomDataObject(BinaryWriter writer, uint clipId, object data)");
            sb.AppendLine("        {");
            sb.AppendLine("            switch (clipId)");
            sb.AppendLine("            {");
            foreach (SkillTypeInfo clip in clips)
            {
                string dataName = SkillCodeGenUtilities.GetNodeDataName(clip);
                sb.AppendLine($"                case SkillGeneratedIds.{SkillCodeGenUtilities.GetIdName(clip)}:");
                sb.AppendLine("                {");
                sb.AppendLine($"                    {dataName} value = data is {dataName} d ? d : default;");
                foreach (FieldInfo field in clip.CustomFields)
                    sb.AppendLine($"                    {SkillCodeGenUtilities.WriteStatement(field.FieldType, $"value.{field.Name}", "writer")}");
                sb.AppendLine("                    break;");
                sb.AppendLine("                }");
            }
            sb.AppendLine("                default: throw new InvalidOperationException($\"No generated custom data writer for clip id {clipId}.\");");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        public void BuildDebugFields(uint clipId, object data, List<SkillCustomFieldDebugEntry> fields)");
            sb.AppendLine("        {");
            sb.AppendLine("            fields.Clear();");
            sb.AppendLine("            switch (clipId)");
            sb.AppendLine("            {");
            foreach (SkillTypeInfo clip in clips)
            {
                string dataName = SkillCodeGenUtilities.GetNodeDataName(clip);
                sb.AppendLine($"                case SkillGeneratedIds.{SkillCodeGenUtilities.GetIdName(clip)}:");
                sb.AppendLine("                {");
                sb.AppendLine($"                    {dataName} value = data is {dataName} d ? d : default;");
                foreach (FieldInfo field in clip.CustomFields)
                    sb.AppendLine($"                    Add(fields, \"{field.Name}\", value.{field.Name});");
                sb.AppendLine("                    break;");
                sb.AppendLine("                }");
            }
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        /// <summary>生成 5 个 SpecialData editor 方法：Capture/Apply/Write/Read/BuildDebugFields。</summary>
        private static void AppendSpecialDataMethods(StringBuilder sb, List<SkillTypeInfo> specialDatas)
        {
            sb.AppendLine("        public object CaptureSpecialData(uint specialDataId, object instance)");
            sb.AppendLine("        {");
            sb.AppendLine("            switch (specialDataId)");
            sb.AppendLine("            {");
            foreach (SkillTypeInfo specialData in specialDatas)
            {
                sb.AppendLine($"                case SkillGeneratedIds.{SkillCodeGenUtilities.GetIdName(specialData)}:");
                sb.AppendLine("                {");
                sb.AppendLine($"                    {SkillCodeGenUtilities.GetTypeName(specialData.Type)} typed = ({SkillCodeGenUtilities.GetTypeName(specialData.Type)})instance;");
                sb.AppendLine($"                    return new {SkillCodeGenUtilities.GetSpecialDataName(specialData)} {{ {string.Join(", ", specialData.CustomFields.Select(f => $"{f.Name} = typed.{f.Name}"))} }};");
                sb.AppendLine("                }");
            }
            sb.AppendLine("                default: throw new InvalidOperationException($\"No generated special data capture for id {specialDataId}.\");");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        public void ApplySpecialData(uint specialDataId, object instance, object data)");
            sb.AppendLine("        {");
            sb.AppendLine("            switch (specialDataId)");
            sb.AppendLine("            {");
            foreach (SkillTypeInfo specialData in specialDatas)
            {
                string runtimeName = SkillCodeGenUtilities.GetSpecialDataName(specialData);
                sb.AppendLine($"                case SkillGeneratedIds.{SkillCodeGenUtilities.GetIdName(specialData)}:");
                sb.AppendLine("                {");
                sb.AppendLine($"                    {SkillCodeGenUtilities.GetTypeName(specialData.Type)} typed = ({SkillCodeGenUtilities.GetTypeName(specialData.Type)})instance;");
                sb.AppendLine($"                    {runtimeName} value = data is {runtimeName} d ? d : default;");
                foreach (FieldInfo field in specialData.CustomFields)
                    sb.AppendLine($"                    typed.{field.Name} = value.{field.Name};");
                sb.AppendLine("                    break;");
                sb.AppendLine("                }");
            }
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        public void WriteSpecialData(BinaryWriter writer, uint specialDataId, object instance)");
            sb.AppendLine("        {");
            sb.AppendLine("            WriteSpecialDataObject(writer, specialDataId, CaptureSpecialData(specialDataId, instance));");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        public object ReadSpecialData(BinaryReader reader, uint specialDataId)");
            sb.AppendLine("        {");
            sb.AppendLine("            switch (specialDataId)");
            sb.AppendLine("            {");
            foreach (SkillTypeInfo specialData in specialDatas)
            {
                string typeName = SkillCodeGenUtilities.GetTypeName(specialData.Type);
                sb.AppendLine($"                case SkillGeneratedIds.{SkillCodeGenUtilities.GetIdName(specialData)}:");
                sb.AppendLine("                {");
                sb.AppendLine($"                    {typeName} obj = ({typeName})Activator.CreateInstance(typeof({typeName}));");
                foreach (FieldInfo field in specialData.CustomFields)
                    sb.AppendLine($"                    obj.{field.Name} = {SkillCodeGenUtilities.ReadExpression(field.FieldType, "reader")};");
                sb.AppendLine("                    return obj;");
                sb.AppendLine("                }");
            }
            sb.AppendLine("                default: throw new InvalidOperationException($\"No generated special data reader for id {specialDataId}.\");");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        private static void WriteSpecialDataObject(BinaryWriter writer, uint specialDataId, object data)");
            sb.AppendLine("        {");
            sb.AppendLine("            switch (specialDataId)");
            sb.AppendLine("            {");
            foreach (SkillTypeInfo specialData in specialDatas)
            {
                string runtimeName = SkillCodeGenUtilities.GetSpecialDataName(specialData);
                sb.AppendLine($"                case SkillGeneratedIds.{SkillCodeGenUtilities.GetIdName(specialData)}:");
                sb.AppendLine("                {");
                sb.AppendLine($"                    {runtimeName} value = data is {runtimeName} d ? d : default;");
                foreach (FieldInfo field in specialData.CustomFields)
                    sb.AppendLine($"                    {SkillCodeGenUtilities.WriteStatement(field.FieldType, $"value.{field.Name}", "writer")}");
                sb.AppendLine("                    break;");
                sb.AppendLine("                }");
            }
            sb.AppendLine("                default: throw new InvalidOperationException($\"No generated special data writer for id {specialDataId}.\");");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        public void BuildSpecialDataDebugFields(uint specialDataId, object data, List<SkillCustomFieldDebugEntry> fields)");
            sb.AppendLine("        {");
            sb.AppendLine("            fields.Clear();");
            sb.AppendLine("            switch (specialDataId)");
            sb.AppendLine("            {");
            foreach (SkillTypeInfo specialData in specialDatas)
            {
                string runtimeName = SkillCodeGenUtilities.GetSpecialDataName(specialData);
                sb.AppendLine($"                case SkillGeneratedIds.{SkillCodeGenUtilities.GetIdName(specialData)}:");
                sb.AppendLine("                {");
                sb.AppendLine($"                    {runtimeName} value = data is {runtimeName} d ? d : default;");
                foreach (FieldInfo field in specialData.CustomFields)
                    sb.AppendLine($"                    Add(fields, \"{field.Name}\", value.{field.Name});");
                sb.AppendLine("                    break;");
                sb.AppendLine("                }");
            }
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void AppendEditorHelpers(StringBuilder sb)
        {
            sb.AppendLine("        private static void Add(List<SkillCustomFieldDebugEntry> fields, string name, object value)");
            sb.AppendLine("        {");
            sb.AppendLine("            fields.Add(new SkillCustomFieldDebugEntry { name = name, value = FormatDebugValue(value) });");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static string FormatDebugValue(object value)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (value == null) return string.Empty;");
            sb.AppendLine("            if (value is Array array)");
            sb.AppendLine("            {");
            sb.AppendLine("                List<string> items = new();");
            sb.AppendLine("                foreach (object item in array)");
            sb.AppendLine("                    items.Add(item != null ? item.ToString() : string.Empty);");
            sb.AppendLine("                return \"[\" + string.Join(\", \", items) + \"]\";");
            sb.AppendLine("            }");
            sb.AppendLine("            return value.ToString();");
            sb.AppendLine("        }");
            sb.AppendLine();
            SkillCodeGenUtilities.AppendArrayHelpers(sb, "        ");
            SkillCodeGenUtilities.AppendVectorHelpers(sb, "        ");
        }
    }
}

#endif
